### PR TITLE
Check if Schema is a function

### PR DESCRIPTION
**Pull request by alanhr**
I created this condition because sometime schema return a function

### CODE REVIEW

**Comment by seanemmer** [comment]
Hi Alan,

I'm having trouble seeing which lines changed in your PR - also, it looks like there are merge conflicts with the master branch after your unit test commits.  Can you resubmit?

Best,
Sean

**Comment by alanhr** [comment]
Hi @seanemmer , you can  remove this pr because in  the another pr ,has also  these modifications.
Sorry, My english is not good ;)

**Comment by seanemmer** [comment]
Great, thanks for your contribution @alanhr 
I'll push these updates to NPM!

**Comment by alanhr** [comment]
@seanemmer  :), When I have  a free time I'll go work in new features for lib.

**Pull request closed without merging**
